spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/healthdb
    username: healthuser
    password: StrongP@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dev
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
  web:
    resources:
      static-locations: classpath:/static/, file:./uploads/
      cache:
        period: 3600

# JWT Configuration
jwt:
  secret: MediSync2026SecretKeyForJWTTokenGenerationAndValidation!@#$%^&*
  expiration: 86400000

# Razorpay Test Mode
razorpay:
  key-id: rzp_test_TBpvX3JOmglohp
  key-secret: I1UtmcRGNH0oWEyOmNGj19dN
